# Generated by Django 4.2.4 on 2023-09-03 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_users_gender"),
        ("leave", "0002_leaverequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaverequest",
            old_name="employee",
            new_name="user",
        ),
        migrations.CreateModel(
            name="UserLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.IntegerField(null=True)),
                ("days_remaining", models.IntegerField(blank=True, null=True)),
                (
                    "leaves",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leave.leavetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
        ),
    ]
