# Generated by Django 4.2.4 on 2023-09-03 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0003_rename_employee_leaverequest_user_userleaves"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userleaves",
            old_name="leaves",
            new_name="leave_type",
        ),
    ]
