# Generated by Django 4.2.4 on 2023-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.IntegerField(unique=True)),
                ("email_address", models.TextField(blank=True, null=True)),
                ("password", models.CharField(max_length=100)),
                ("last_login", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
