# Generated by Django 4.2.4 on 2023-08-31 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_name",
        ),
    ]
