# Generated by Django 4.2.4 on 2023-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
