# Generated by Django 4.2.4 on 2023-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_first_name_users_name_remove_users_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.CharField(max_length=100),
        ),
    ]
